version: '3'
services:
  ui:
    build: ./food-journal
    container_name: ui
    restart: always
    expose:
      - 80

  nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
        - "8002:80"
