version: '3'
services:
  ui:
    build: ./food-journal
    container_name: ui
    restart: always
    volumes:
      - "./food-journal:/app"
      - /app/node_modules
    ports:
      - 80:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
